- block:
    - include: identity/user.yml
    - include: identity/service.yml
    - include: identity/endpoints.yml

  environment:
    OS_PROJECT_DOMAIN_NAME:  default
    OS_USER_DOMAIN_NAME:     default
    OS_PROJECT_NAME:         admin
    OS_USERNAME:             admin
    OS_PASSWORD:             '{{ openstack_admin_password }}'
    OS_AUTH_URL:             http://controller:35357/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION:    2
