- name:          Check if node is already present in the ring.
  command:       'swift-ring-builder {{ ring.name }}.builder search --zone {{ zone }} --ip {{ ip }} --device {{ device }}'
  ignore_errors: yes
  register:      node_presence_check
  changed_when:  no
  args:
    chdir: /etc/swift

- name:    Add storage node to the ring.
  command: 'swift-ring-builder {{ ring.name }}.builder add --region 1 --zone {{ zone }} --ip {{ ip }} --port {{ ring.port }} --device {{ device }} --weight 100'
  args:
    chdir: /etc/swift
  when: '{{ ip not in node_presence_check.stdout }}'
